#define COMMAND 1
#define ID 2
#define ENTERO 3
#define DECIMAL 4
#define STRING 5
#define TYPE 6
#define OPERATOR 7
#define EQ 8
#define AST 9
#define PARABRE 10
#define PARACIERR 11
#define COMA 12
#define PUNTCOMA 13
#define DOSPUNT 14
#define INSERT 15
#define DELETE 16
#define ERROR 17
#define SELECT 18
#define INTO 19
#define FROM 20
#define VALUES 21
#define WHERE 22
#define SET 23 
#define GRPBY 24
#define ORDBY 25